// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLDeleter is an autogenerated mock type for the URLDeleter type
type URLDeleter struct {
	mock.Mock
}

// DeleteURL provides a mock function with given fields: alias
func (_m *URLDeleter) DeleteURL(alias string) error {
	ret := _m.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLDeleter creates a new instance of URLDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLDeleter {
	mock := &URLDeleter{}
	mock.Mock.Test(t) //  Позволяет testify/mock использовать t для вывода ошибок и другой информации, связанной с тестом. Например, когда мок обнаруживает, что ожидание не было выполнено, или метод был вызван с неправильными аргументами, он будет сообщать об этом через t.Errorf или t.Fatalf.

	// mock.AssertExpectations(t) — это метод из testify/mock, который проверяет, были ли все предварительно настроенные ожидания (с использованием On(...)) для данного мок-объекта выполнены. То есть, были ли вызваны все ожидаемые методы с ожидаемыми аргументами и требуемое количество раз.
	t.Cleanup(func() { mock.AssertExpectations(t) }) // Она регистрирует функцию, которая будет выполнена после завершения текущего теста, независимо от того, прошел он успешно или завершился ошибкой

	return mock
}
